-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 14:07:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema letsorganize
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema letsorganize
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `letsorganize` DEFAULT CHARACTER SET utf8 ;
USE `letsorganize` ;

-- -----------------------------------------------------
-- Table `letsorganize`.`clothes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `letsorganize`.`clothes` (
  `idcolthes` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `imageUrl` VARCHAR(1000) NOT NULL,
  `inStock` VARCHAR(45) NOT NULL,
  `articleLeft` INT NULL,
  PRIMARY KEY (`idcolthes`),
  UNIQUE INDEX `idcolthes_UNIQUE` (`idcolthes` ASC) VISIBLE);



